default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: Davidrama

development:
  <<: *default
  database: hello-rails-development

test:
  <<: *default
  database: hello-rails-test

production:
  <<: *default
  database: hello-rails-production
